version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    environment:
      - TZ=Asia/Shanghai
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - 45554:80
      - 45555:443
